import { chromium } from 'file:///C:/Users/akals/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root='C:/Users/akals/Documents/GitHub/dungeon/art/sprites-v2';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1120,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///'+root+'/pixel-editor.html');
await page.evaluate(()=>localStorage.clear());await page.reload();
const initial=await page.evaluate(()=>pixels.map(r=>r.join('')));
await page.locator('#mirror').check();await page.getByRole('button',{name:'머리 밝음',exact:true}).click();
const box=await page.locator('#board').boundingBox();
await page.mouse.click(box.x+box.width/32,box.y+box.height/32);
assert.equal(await page.evaluate(()=>pixels[0][0]),'H');assert.equal(await page.evaluate(()=>pixels[0][15]),'H');
await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),initial);
await page.locator('#redo').click();assert.equal(await page.evaluate(()=>pixels[0][15]),'H');
await page.locator('#mirror').uncheck();await page.locator('#erase').click();
await page.mouse.move(box.x+box.width*5.5/16,box.y+box.height*.5/16);await page.mouse.down();await page.mouse.move(box.x+box.width*9.5/16,box.y+box.height*.5/16,{steps:4});await page.mouse.up();
assert.equal(await page.evaluate(()=>pixels[0].slice(5,10).join('')),'.....');await page.locator('#undo').click();assert.equal(await page.evaluate(()=>pixels[0].slice(5,10).join('')),'#####');
const draft=await page.evaluate(()=>pixels.map(r=>r.join('')));await page.reload();assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),draft);
const pngEvent=page.waitForEvent('download');await page.locator('#png').click();await (await pngEvent).saveAs(root+'/editor-export-test.png');
const jsonEvent=page.waitForEvent('download');await page.locator('#json').click();await (await jsonEvent).saveAs(root+'/editor-export-test.json');
await page.locator('#reset').click();await page.locator('#import').setInputFiles(root+'/editor-export-test.json');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('불러왔'));
assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),draft);
await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"size":32}')});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('기존 작업'));
assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),draft);
await page.locator('#reset').click();await page.screenshot({path:root+'/pixel-editor-preview.png',fullPage:true});
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: paint, mirror, stroke undo, redo, draft reload, PNG/JSON export, import, invalid import, mobile width, no page errors');
