import {chromium} from 'file:///C:/Users/akals/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root='C:/Users/akals/Documents/GitHub/dungeon/art/sprites-v2';
const approved=JSON.parse(await fs.readFile(root+'/approved-warrior-front.json','utf8'));
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1280,height:1050}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('file:///'+root+'/parts-editor.html');
assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),approved.rows);
assert.equal(await page.locator('#headPick option').count(),12);
assert.equal(await page.locator('#jobPick option').count(),3);
await page.getByRole('button',{name:'머리 밝음',exact:true}).click();
const box=await page.locator('#board').boundingBox();await page.mouse.click(box.x+box.width/32,box.y+box.height/32);
await page.locator('#headPick').selectOption('F7');await page.locator('#jobPick').selectOption('archer');await page.locator('#dirPick').selectOption('back');await page.locator('#phasePick').selectOption('2');
assert.equal(await page.evaluate(()=>pixels.flat().includes('E')),false);
await page.locator('#headPick').selectOption('M1');await page.locator('#jobPick').selectOption('warrior');await page.locator('#dirPick').selectOption('front');await page.locator('#phasePick').selectOption('-1');
assert.equal(await page.evaluate(()=>pixels[0][0]),'H');
await page.locator('#reset').click();assert.deepEqual(await page.evaluate(()=>pixels.map(r=>r.join(''))),approved.rows);
const sheetWait=page.waitForEvent('download');await page.locator('#sheet').click();await (await sheetWait).saveAs(root+'/production/verified-export-sheet.png');
const bundleWait=page.waitForEvent('download');await page.locator('#allSave').click();await (await bundleWait).saveAs(root+'/production/verified-edits.json');
await page.locator('#allOpen').setInputFiles(root+'/production/verified-edits.json');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('불러왔'));
await page.screenshot({path:root+'/production/parts-editor-preview.png',fullPage:true});
await page.goto('file:///'+root+'/production/index.html');await page.locator('#head').selectOption('F3');await page.locator('#job').selectOption('rogue');await page.locator('#pause').click();
await page.screenshot({path:root+'/production/gallery-preview.png',fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: approved front exact, selectors, independent edits, reset, sheet and bundle export/import, gallery, no page errors');
